"""Streamlit app for PL Temp Fit workflow.\nGenerated by Copilot"""

from pathlib import Path

import pandas as pd
import streamlit as st
from app_utils.config_utils import generate_and_save_model_config
from app_utils.data_utils import (
    ensure_directories,
    load_and_plot_data,
    modify_and_plot_data,
)
from app_utils.lifetime_utils import read_lifetime_data
from app_utils.params_utils import model_parameters_form

from pl_temp_fit import Exp_data_utils, config_utils, fit_pl_utils
from pl_temp_fit.data_generators import PLAbsandAlllifetime


def run_fit(
    model_config_save,
):
    csv_name_pl = model_config_save["csv_name_pl"]
    save_folder = model_config_save["save_folder"]
    Path(save_folder).mkdir(parents=True, exist_ok=True)
    # Load the data
    Exp_data_pl, temperature_list_pl, hws_pl = Exp_data_utils.read_data(
        csv_name_pl
    )
    # initialising the data generator
    pl_data_gen = PLAbsandAlllifetime.PLAbsandAlllifetime(
        temperature_list_pl, hws_pl
    )
    pl_data_gen.relative_error_lifetime = model_config_save[
        "relative_error_lifetime"
    ]
    pl_data_gen.error_in_max_abs_pos = model_config_save[
        "error_in_max_abs_pos"
    ]
    pl_data_gen.max_abs_pos_exp = model_config_save["max_abs_pos_exp"]
    pl_data_gen.temperature_lifetimes_exp = model_config_save[
        "temperature_lifetimes_exp"
    ]
    pl_data_gen.update_with_model_config(model_config_save)

    co_var_mat_pl, variance_pl = pl_data_gen.get_covariance_matrix()
    # getting the maximum likelihood estimate
    get_maximum_likelihood_estimate = False
    fit_pl_utils.run_sampler_parallel(
        save_folder,
        Exp_data_pl,
        co_var_mat_pl,
        pl_data_gen,
        nsteps=500,  # model_config_save["nsteps"],
        coeff_spread=model_config_save["coeff_spread"] * 3,
        num_coords=model_config_save["num_coords"],
        restart_sampling=False,
    )


def main():
    # st.title("PL Temp Fit Workflow App")
    st.set_page_config(
        page_title="PL Temp Fit Workflow",
        page_icon=":microscope:",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    # --- File selection ---
    with st.sidebar:
        st.header("Folders")
        figures_dir = st.text_input("Figures Directory", value="figures")
        fit_data_base_dir = st.text_input(
            "Fit Data Base Directory", value="fit_data_base"
        )
        fit_data_dir = st.text_input("Fit Data Directory", value="fit_data")

    ensure_directories(figures_dir, fit_data_base_dir, fit_data_dir)
    st.header("Data Files")
    col1, col2, col3 = st.columns(3)
    with col1:
        csv_name = st.text_input(
            "PL Data CSV Filename", value="example_PL_data_Y6.csv"
        )
    with col2:
        lifetime_csv = st.text_input(
            "Lifetime Data CSV Filename", value="temperature_lifetimes_exp.csv"
        )

    with col3:
        if st.button("Load Experimental Data"):
            if not Path(csv_name).exists():
                st.error(f"File {csv_name} does not exist.")
                return
            if not Path(lifetime_csv).exists():
                st.error(f"File {lifetime_csv} does not exist.")
                return

            Exp_data, temperature_list, hws, fig, fig_path = (
                load_and_plot_data(csv_name, figures_dir)
            )
            st.session_state["exp_data"] = Exp_data
            st.session_state["temperature_list"] = temperature_list
            st.session_state["hws"] = hws
            st.session_state["pl_fig"] = fig
            st.session_state["fig_path"] = fig_path
            temperature_lifetimes_exp, max_abs_pos_exp = read_lifetime_data(
                lifetime_csv
            )
            st.session_state["temperature_lifetimes_exp"] = (
                temperature_lifetimes_exp
            )
            st.session_state["max_abs_pos_exp"] = max_abs_pos_exp
            st.session_state["table_data"] = {
                "Temperature (K)": [
                    float(x.replace("K", ""))
                    for x in temperature_lifetimes_exp.keys()
                ],
                "Lifetime (ns)": [
                    x * 1e9 for x in temperature_lifetimes_exp.values()
                ],
                "Max Abs Pos Exp": [max_abs_pos_exp]
                * len(temperature_lifetimes_exp),
            }
            st.session_state["table_data"] = pd.DataFrame(
                st.session_state["table_data"]
            )
            st.session_state["csv_name"] = csv_name

    # --- Step 2: Modify experimental data ---
    st.header("2. Modify Experimental Data (Wavelength Range)")
    col1, col2 = st.columns([2, 3])
    with col1:
        st.subheader("Modification Controls")
        st.session_state.hws_limits = st.slider(
            "Wavelength Range (hws_limits)",
            min_value=min(st.session_state["hws"]),
            max_value=max(st.session_state["hws"]),
            value=st.session_state.get("hws_limits", (0.8, 1.7)),
            step=0.01,
        )
        step = st.number_input(
            "Step",
            value=0.01,
            min_value=0.001,
            max_value=0.1,
            step=0.001,
            format="%0.3f",
        )
        temperature_list = st.session_state.get("temperature_list", [])

        temperature_list = st.multiselect(
            "Select Temperatures",
            options=temperature_list,
            default=temperature_list,
        )
        if "table_data" in st.session_state:
            table_data = st.session_state["table_data"]
            st.dataframe(
                table_data[
                    table_data["Temperature (K)"].isin(temperature_list)
                ]
            )
        if st.button("Modify and Plot Data"):
            Exp_data, temperature_list, hws, fig, fig_path, xsc_name = (
                modify_and_plot_data(
                    csv_name,
                    st.session_state.hws_limits,
                    step,
                    temperature_list,
                    figures_dir,
                )
            )
            st.session_state["csv_name"] = xsc_name
            if fig is not None:
                st.session_state["pl_fig"] = fig
                st.session_state["exp_data"] = Exp_data
                st.session_state["temperature_list"] = temperature_list
                st.session_state["hws"] = hws
                st.session_state["fig_path"] = fig_path
                st.info(f"Modified data: {xsc_name}")
    with col2:
        st.subheader("PL Data Plot")
        if "pl_fig" in st.session_state:
            st.pyplot(st.session_state["pl_fig"])
            st.caption(
                f"Figure saved to {st.session_state.get('fig_path', '')}"
            )
        else:
            st.info("No plot to display yet.")

    # --- Step 4: Model parameters ---
    st.header("4. Model Parameters and Config Generation")
    params = model_parameters_form()
    id_of_the_fit = st.text_input(
        "ID of the Fit",
        value="fit_1",
        help="This ID will be used to save the model configuration.",
    )
    if st.button("Generate and Save Model Config"):
        Exp_data = st.session_state.get("exp_data")
        temperature_list = st.session_state.get("temperature_list")
        hws = st.session_state.get("hws")
        if Exp_data is None or temperature_list is None or hws is None:
            Exp_data, temperature_list, hws, _, _ = load_and_plot_data(
                csv_name, figures_dir
            )
        temperature_lifetimes_exp = st.session_state.get(
            "temperature_lifetimes_exp"
        )
        max_abs_pos_exp = st.session_state.get("max_abs_pos_exp")
        if temperature_lifetimes_exp is None or max_abs_pos_exp is None:
            temperature_lifetimes_exp, max_abs_pos_exp = read_lifetime_data(
                lifetime_csv
            )

        model_config, test_id = generate_and_save_model_config(
            params,
            csv_name,
            temperature_list,
            hws,
            temperature_lifetimes_exp,
            max_abs_pos_exp,
            fit_data_base_dir,
            fit_data_dir,
            test_id=id_of_the_fit,
        )
        st.success(f"Model config saved. Test ID: {test_id}")
        st.session_state["model_config"] = model_config
        st.session_state["test_id"] = test_id

    if st.button("plot fit limits"):
        if "test_id" not in st.session_state:
            st.error("Please generate and save the model config first.")
            return

        model_config, model_config_save = config_utils.load_model_config(
            st.session_state["test_id"],
            database_folder=str(Path(fit_data_base_dir) / ""),
        )

        fig, ax = fit_pl_utils.plot_fit_limits_overlay(
            model_config, model_config_save
        )
        st.pyplot(fig)

    if st.button("Run Fit"):
        if "test_id" not in st.session_state:
            st.error("Please generate and save the model config first.")
            return

        model_config, model_config_save = config_utils.load_model_config(
            st.session_state["test_id"],
            database_folder=str(Path(fit_data_base_dir) / ""),
        )
        run_fit(model_config_save)
        st.success("Fit completed successfully.")


if __name__ == "__main__":
    main()
