"""Streamlit app for PL Temp Fit workflow.\nGenerated by Copilot"""

import io
from pathlib import Path

import pandas as pd
import streamlit as st

from pl_temp_fit import Exp_data_utils, config_utils, fit_pl_utils
from pl_temp_fit.app_utils.config_utils import generate_and_save_model_config
from pl_temp_fit.app_utils.data_utils import (
    ensure_directories,
    load_and_plot_data,
    modify_and_plot_data,
)
from pl_temp_fit.app_utils.lifetime_utils import read_lifetime_data
from pl_temp_fit.app_utils.params_utils import model_parameters_form
from pl_temp_fit.app_utils.plot_display_utils import (
    plot_selection,
    read_results,
)
from pl_temp_fit.app_utils.plot_utils_interactive import (
    plot_fit_limits_overlay_interactive,
    plot_state_diagram_interactive,
)
from pl_temp_fit.data_generators import PLAbsandAlllifetime


def run_fit(
    model_config_save,
    status_placeholder=None,
    progress_bar=None,
):
    csv_name_pl = model_config_save["csv_name_pl"]
    save_folder = model_config_save["save_folder"]
    Path(save_folder).mkdir(parents=True, exist_ok=True)

    if status_placeholder:
        status_placeholder.info("📂 Loading experimental data...")
    if progress_bar:
        progress_bar.progress(0.1)

    # Load the data
    Exp_data_pl, temperature_list_pl, hws_pl = Exp_data_utils.read_data(
        csv_name_pl
    )

    if status_placeholder:
        status_placeholder.info("🔧 Initializing data generator...")
    if progress_bar:
        progress_bar.progress(0.2)

    # initialising the data generator
    pl_data_gen = PLAbsandAlllifetime.PLAbsandAlllifetime(
        temperature_list_pl, hws_pl
    )
    pl_data_gen.relative_error_lifetime = model_config_save[
        "relative_error_lifetime"
    ]
    pl_data_gen.error_in_max_abs_pos = model_config_save[
        "error_in_max_abs_pos"
    ]
    pl_data_gen.max_abs_pos_exp = model_config_save["max_abs_pos_exp"]
    pl_data_gen.temperature_lifetimes_exp = model_config_save[
        "temperature_lifetimes_exp"
    ]
    pl_data_gen.update_with_model_config(model_config_save)

    if status_placeholder:
        status_placeholder.info("📊 Computing covariance matrix...")
    if progress_bar:
        progress_bar.progress(0.3)

    co_var_mat_pl, variance_pl = pl_data_gen.get_covariance_matrix()

    if status_placeholder:
        status_placeholder.info(
            "🚀 Running MCMC sampler... This may take several minutes."
        )
    if progress_bar:
        progress_bar.progress(0.4)

    # getting the maximum likelihood estimate
    get_maximum_likelihood_estimate = False
    fit_pl_utils.run_sampler_parallel(
        save_folder,
        Exp_data_pl,
        co_var_mat_pl,
        pl_data_gen,
        nsteps=model_config_save["nsteps"],
        coeff_spread=model_config_save["coeff_spread"] * 3,
        num_coords=model_config_save["num_coords"],
        restart_sampling=False,
    )

    if status_placeholder:
        status_placeholder.success("✅ Fitting completed!")
    if progress_bar:
        progress_bar.progress(1.0)


def display_workflow_status():
    """Display the current workflow status with indicators."""
    st.sidebar.markdown("---")
    st.sidebar.subheader("🔄 Workflow Status")

    # Check status of each step
    data_loaded = "exp_data" in st.session_state
    config_saved = "test_id" in st.session_state
    fit_completed = "reader" in st.session_state

    status_items = [
        ("📂 Data Loaded", data_loaded),
        ("⚙️ Config Saved", config_saved),
        ("🔄 Fit Completed", fit_completed),
    ]

    for label, status in status_items:
        if status:
            st.sidebar.success(f"{label} ✅")
        else:
            st.sidebar.info(f"{label} ⏳")


def data_management_tab():
    """Combined tab for data loading and modification with interactive plots."""
    st.header("📂 Data Management & Modification")

    # Create two main sections
    col_controls, col_plots = st.columns([1, 2])

    with col_controls:
        # File Configuration Section
        with st.expander("📁 File Configuration", expanded=True):
            tab_selection = st.selectbox(
                "Select upload tool:", ["Using paths", "Upload files"]
            )
            if tab_selection == "Using paths":
                st.session_state["csv_name"] = st.text_input(
                    "PL Data CSV Filename",
                    value="experimental_data/y6_example/example_PL_data_Y6.csv",
                    help="CSV file containing photoluminescence data",
                )
                st.session_state["lifetime_csv"] = st.text_input(
                    "Lifetime Data CSV Filename",
                    value="experimental_data/y6_example/temperature_lifetimes_exp.csv",
                    help="CSV file containing lifetime measurements",
                )
            if tab_selection == "Upload files":
                st.session_state["csv_name"] = st.file_uploader(
                    "Upload PL Data CSV",
                    type=["csv"],
                    help="Upload your photoluminescence data CSV file",
                )
                st.session_state["lifetime_csv"] = st.file_uploader(
                    "Upload Lifetime Data CSV",
                    type=["csv"],
                    help="Upload your lifetime measurements CSV file",
                )
        # Data Loading Section
        with st.expander("📊 Load Data", expanded=True):
            # File validation
            if st.session_state.get("csv_name", None) is None:
                st.warning("⚠️ Please provide a PL data CSV file")
                return
            
            csv_exists = Path(
                st.session_state.get("csv_name", "not_loaded")
            ).exists()
            lifetime_exists = Path(
                st.session_state.get("lifetime_csv", "not_loaded")
            ).exists()

            st.write(
                f"PL Data File: {'✅' if csv_exists else '❌'} {st.session_state.get('csv_name', '')}"
            )
            st.write(
                f"Lifetime File: {'✅' if lifetime_exists else '❌'} {st.session_state.get('lifetime_csv', '')}"
            )

            if st.button(
                "🚀 Load Experimental Data",
                type="primary",
                disabled=not (csv_exists and lifetime_exists),
            ):
                with st.spinner("Loading experimental data..."):
                    try:
                        (
                            exp_data,
                            temperature_list,
                            hws,
                            fig_interactive,
                            fig_matplotlib,
                            fig_path,
                        ) = load_and_plot_data(
                            st.session_state.get("csv_name", ""),
                            st.session_state.get("figures_dir", "figures"),
                        )
                        st.session_state["exp_data"] = exp_data
                        st.session_state["original_exp_data"] = (
                            exp_data.copy()
                        )  # Store original
                        st.session_state["original_hws"] = (
                            hws.copy()
                        )  # Store original
                        st.session_state["temperature_list"] = temperature_list
                        st.session_state["hws"] = hws
                        st.session_state["pl_fig_interactive"] = (
                            fig_interactive
                        )
                        st.session_state["pl_fig_matplotlib"] = fig_matplotlib
                        st.session_state["fig_path"] = fig_path

                        temperature_lifetimes_exp, max_abs_pos_exp = (
                            read_lifetime_data(lifetime_csv)
                        )
                        st.session_state["temperature_lifetimes_exp"] = (
                            temperature_lifetimes_exp
                        )
                        st.session_state["max_abs_pos_exp"] = max_abs_pos_exp

                        # Create summary table
                        st.session_state["table_data"] = pd.DataFrame(
                            {
                                "Temperature (K)": [
                                    float(x.replace("K", ""))
                                    for x in temperature_lifetimes_exp.keys()
                                ],
                                "Lifetime (ns)": [
                                    x * 1e9
                                    for x in temperature_lifetimes_exp.values()
                                ],
                                "Max Abs Pos Exp": [max_abs_pos_exp]
                                * len(temperature_lifetimes_exp),
                            }
                        )
                        # st.session_state["csv_name"] = csv_name
                        st.success("✅ Data loaded successfully!")

                    except Exception as e:
                        st.error(f"❌ Error loading data: {e!s}")

        # Data Modification Section
        if "exp_data" in st.session_state:
            st.markdown("---")
            with st.expander("🔧 Data Modification", expanded=True):
                # Wavelength range control
                hws = st.session_state.get("hws", [0.8, 1.7])
                st.session_state.hws_limits = [min(hws), max(hws)]
                col1, col2 = st.columns(2)
                with col1:
                    st.session_state.hws_limits[0] = st.number_input(
                        "⬅️ Min Wavelength (eV)",
                        value=st.session_state.hws_limits[0],
                        min_value=float(min(hws)),
                        max_value=float(max(hws) - 0.01),
                        step=0.01,
                        key="hws_min",
                    )
                with col2:
                    st.session_state.hws_limits[1] = st.number_input(
                        "➡️ Max Wavelength (eV)",
                        value=st.session_state.hws_limits[1],
                        min_value=float(min(hws) + 0.01),
                        max_value=float(max(hws)),
                        step=0.01,
                        key="hws_max",
                    )

                # Step size control
                step = st.number_input(
                    "📏 Step Size",
                    value=0.01,
                    min_value=0.001,
                    max_value=0.1,
                    step=0.001,
                    format="%0.3f",
                    help="Resolution for data interpolation",
                )

                # Temperature selection
                temperature_list = st.session_state.get("temperature_list", [])
                selected_temperatures = st.multiselect(
                    "🌡️ Select Temperatures",
                    options=temperature_list,
                    default=temperature_list,
                    help="Choose which temperatures to include in analysis",
                )

                # Modify button
                if st.button("🔄 Apply Modifications", type="secondary"):
                    with st.spinner("Modifying data..."):
                        try:
                            csv_name = st.session_state.get("csv_name", "")
                            figures_dir = st.session_state.get(
                                "figures_dir", "figures"
                            )
                            original_data = st.session_state.get(
                                "original_exp_data"
                            )
                            original_hws = st.session_state.get("original_hws")

                            result = modify_and_plot_data(
                                csv_name,
                                st.session_state.hws_limits,
                                step,
                                selected_temperatures,
                                figures_dir,
                                original_data,
                                original_hws,
                            )

                            (
                                exp_data,
                                temperature_list,
                                hws,
                                fig_interactive,
                                fig_comparison,
                                fig_matplotlib,
                                fig_path,
                                xsc_name,
                            ) = result

                            # Update session state
                            st.session_state["csv_name"] = xsc_name
                            st.session_state["pl_fig_interactive"] = (
                                fig_interactive
                            )
                            st.session_state["pl_fig_comparison"] = (
                                fig_comparison
                            )
                            st.session_state["pl_fig_matplotlib"] = (
                                fig_matplotlib
                            )
                            st.session_state["exp_data"] = exp_data
                            st.session_state["temperature_list"] = (
                                temperature_list
                            )
                            st.session_state["hws"] = hws
                            st.session_state["fig_path"] = fig_path

                            st.success(f"✅ Data modified: {xsc_name}")

                        except Exception as e:
                            st.error(f"❌ Error modifying data: {e!s}")

        # Data Summary
        if "table_data" in st.session_state:
            with st.expander("📋 Data Summary", expanded=False):
                st.dataframe(st.session_state["table_data"], width="stretch")

    with col_plots:
        st.subheader("📈 Interactive Data Visualization")

        # Plot selection tabs
        if "pl_fig_interactive" in st.session_state:
            plot_tab1, plot_tab2 = st.tabs(
                ["📊 Current Data", "🔄 Comparison"]
            )

            with plot_tab1:
                st.plotly_chart(
                    st.session_state["pl_fig_interactive"],
                    width="stretch",
                    key="main_data_plot",
                )
                st.caption(
                    f"Figure saved to {st.session_state.get('fig_path', '')}"
                )

                # Download button for matplotlib version
                if "pl_fig_matplotlib" in st.session_state:
                    fig_buffer = io.BytesIO()
                    st.session_state["pl_fig_matplotlib"].savefig(
                        fig_buffer, format="png", dpi=300, bbox_inches="tight"
                    )
                    fig_buffer.seek(0)
                    st.download_button(
                        label="📥 Download High-Res PNG",
                        data=fig_buffer,
                        file_name=f"pl_data_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}.png",
                        mime="image/png",
                    )

            with plot_tab2:
                if (
                    "pl_fig_comparison" in st.session_state
                    and st.session_state["pl_fig_comparison"] is not None
                ):
                    st.plotly_chart(
                        st.session_state["pl_fig_comparison"],
                        width="stretch",
                        key="comparison_plot",
                    )
                    st.caption("Comparison between original and modified data")
                else:
                    st.info(
                        "📊 Apply data modifications to see comparison plot"
                    )
        else:
            st.info("📊 Load data to see interactive visualization")
            st.markdown("""
            **🎨 Interactive Features:**
            - 🔍 **Zoom & Pan**: Click and drag to zoom, double-click to reset
            - 📊 **Hover Details**: Hover over data points for precise values
            - 👁️ **Legend Toggle**: Click legend items to show/hide data series
            - 📥 **Download**: Use the download button for high-resolution images
            """)


def data_loading_tab():
    """Legacy function - now redirects to combined data management."""
    data_management_tab()


def data_modification_tab():
    """Legacy function - now redirects to combined data management."""
    st.info(
        "📋 Data loading and modification have been combined into the Data Management tab."
    )
    st.markdown(
        "👈 Please use the **Data Management** tab for all data operations."
    )


def model_configuration_tab():
    """Tab for model parameters and configuration."""
    st.header("⚙️ Model Configuration")

    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("🔧 Model Parameters")
        params = model_parameters_form()

        # Test ID input
        st.session_state["test_id"] = st.text_input(
            "🏷️ Fit ID",
            value=st.session_state.get("test_id", "fit_1"),
            help="Unique identifier for this fit configuration",
        )

        # Generate config button
        generate_button = st.button(
            "💾 Generate and Save Config", type="primary"
        )

        if generate_button:
            with st.spinner("Generating model configuration..."):
                # try:
                # Get required data
                Exp_data = st.session_state.get("exp_data")
                temperature_list = st.session_state.get("temperature_list")
                hws = st.session_state.get("hws")

                # Load data if not available
                if Exp_data is None or temperature_list is None or hws is None:
                    csv_name = st.session_state.get(
                        "csv_name", "example_PL_data_Y6.csv"
                    )
                    figures_dir = st.session_state.get(
                        "figures_dir", "figures"
                    )
                    Exp_data, temperature_list, hws, _, _, _ = (
                        load_and_plot_data(csv_name, figures_dir)
                    )

                # Get lifetime data
                temperature_lifetimes_exp = st.session_state.get(
                    "temperature_lifetimes_exp"
                )
                max_abs_pos_exp = st.session_state.get("max_abs_pos_exp")

                if (
                    temperature_lifetimes_exp is None
                    or max_abs_pos_exp is None
                ):
                    lifetime_csv = "temperature_lifetimes_exp.csv"
                    temperature_lifetimes_exp, max_abs_pos_exp = (
                        read_lifetime_data(lifetime_csv)
                    )

                # Generate configuration
                csv_name = st.session_state.get(
                    "csv_name", "example_PL_data_Y6.csv"
                )
                fit_data_base_dir = st.session_state.get(
                    "fit_data_base_dir", "fit_data_base"
                )
                fit_data_dir = st.session_state.get("fit_data_dir", "fit_data")

                model_config, test_id = generate_and_save_model_config(
                    params,
                    csv_name,
                    temperature_list,
                    hws,
                    temperature_lifetimes_exp,
                    max_abs_pos_exp,
                    fit_data_base_dir,
                    fit_data_dir,
                    test_id=st.session_state["test_id"],
                )

                st.session_state["model_config"] = model_config
                st.session_state["test_id"] = test_id
                st.success(f"✅ Model config saved! Test ID: {test_id}")

            # except Exception as e:
            #   st.error(f"❌ Error generating config: {str(e)}")

    with col2:
        st.subheader("📊 Configuration Actions")

        # plot State Diagram
        if st.button("⚡ Plot State Diagram", type="secondary"):
            if "test_id" not in st.session_state:
                st.error("⚠️ Please generate config first")
            else:
                with st.spinner("Generating interactive state diagram..."):
                    try:
                        fit_data_base_dir = st.session_state.get(
                            "fit_data_base_dir", "fit_data_base"
                        )
                        model_config, model_config_save = (
                            config_utils.load_model_config(
                                st.session_state["test_id"],
                                database_folder=str(
                                    Path(fit_data_base_dir) / ""
                                ),
                            )
                        )

                        # Create interactive plot
                        fig_interactive = plot_state_diagram_interactive(
                            model_config_save
                        )

                        # Display the interactive plot
                        st.plotly_chart(fig_interactive, width="stretch")
                        st.info(
                            "💡 **Interactive Features**: Hover over states to see energy levels and parameters"
                        )

                    except Exception as e:
                        st.error(f"❌ Error plotting state diagram: {e!s}")
        # Plot fit limits
        if st.button("📈 Preview Fit Limits", type="secondary"):
            if "test_id" not in st.session_state:
                st.error("⚠️ Please generate config first")
            else:
                with st.spinner("Generating interactive fit limits plot..."):
                    try:
                        fit_data_base_dir = st.session_state.get(
                            "fit_data_base_dir", "fit_data_base"
                        )
                        model_config, model_config_save = (
                            config_utils.load_model_config(
                                st.session_state["test_id"],
                                database_folder=str(
                                    Path(fit_data_base_dir) / ""
                                ),
                            )
                        )

                        # Create interactive plot
                        fig_interactive = plot_fit_limits_overlay_interactive(
                            model_config, model_config_save
                        )

                        # Display the interactive plot
                        st.plotly_chart(fig_interactive, width="stretch")

                        # Also create matplotlib version for comparison/download
                        fig_matplotlib, ax = (
                            fit_pl_utils.plot_fit_limits_overlay(
                                model_config, model_config_save
                            )
                        )

                        # Add download button for matplotlib version
                        fig_buffer = io.BytesIO()
                        fig_matplotlib.savefig(
                            fig_buffer,
                            format="png",
                            dpi=300,
                            bbox_inches="tight",
                        )
                        fig_buffer.seek(0)
                        st.download_button(
                            label="📥 Download High-Res PNG",
                            data=fig_buffer,
                            file_name=f"fit_limits_{st.session_state['test_id']}.png",
                            mime="image/png",
                        )

                    except Exception as e:
                        st.error(f"❌ Error plotting fit limits: {e!s}")


def fitting_tab():
    """Tab for running the fitting process."""
    st.header("🔄 Model Fitting")

    if "test_id" not in st.session_state:
        st.warning("⚠️ Please generate and save model configuration first")
        return

    col1, col2 = st.columns([1, 2])

    with col1:
        st.subheader("🚀 Run Fitting")

        # Display current configuration
        test_id = st.session_state.get("test_id", "")
        st.info(f"📋 Current Config: **{test_id}**")

        # Fitting parameters
        with st.expander("⚙️ Fitting Parameters", expanded=False):
            nsteps = st.number_input(
                "Number of Steps", value=500, min_value=10, max_value=5000
            )
            st.info("💡 More steps = better convergence but longer runtime")

        # Run fit button
        run_fit_button = st.button("🏃‍♂️ Start Fitting", type="primary")

        if run_fit_button:
            # Create live status display in col2
            with col2:
                st.subheader("📈 Fitting Progress")
                status_placeholder = st.empty()
                progress_bar = st.progress(0)
                log_expander = st.expander("📋 Detailed Logs", expanded=True)
                log_text = log_expander.empty()

            with st.spinner(
                "Running MCMC fitting... This may take several minutes."
            ):
                try:
                    fit_data_base_dir = st.session_state.get(
                        "fit_data_base_dir", "fit_data_base"
                    )
                    model_config, model_config_save = (
                        config_utils.load_model_config(
                            st.session_state["test_id"],
                            database_folder=str(Path(fit_data_base_dir) / ""),
                        )
                    )

                    # Update nsteps in config
                    model_config_save["nsteps"] = nsteps

                    # Capture output using context manager
                    import sys
                    from io import StringIO

                    # Redirect stdout to capture print statements
                    old_stdout = sys.stdout
                    sys.stdout = captured_output = StringIO()

                    try:
                        run_fit(
                            model_config_save, status_placeholder, progress_bar
                        )
                    finally:
                        # Restore stdout
                        sys.stdout = old_stdout

                    # Display captured output
                    output_text = captured_output.getvalue()
                    if output_text:
                        log_text.code(output_text, language="text")
                    else:
                        log_text.info("No console output captured")

                    st.success("✅ Fitting completed successfully!")

                    # Auto-load results
                    (
                        st.session_state["reader"],
                        st.session_state["model_config"],
                        st.session_state["model_config_save"],
                    ) = read_results(
                        st.session_state["test_id"],
                        fit_data_base_dir,
                    )
                    st.success("📊 Results loaded automatically!")

                except Exception as e:
                    st.error(f"❌ Fitting failed: {e!s}")
                    import traceback

                    log_text.code(traceback.format_exc(), language="python")

        # Load results section
        st.markdown("---")
        st.subheader("📊 Load Results")

        if st.button("📖 Load Existing Results", type="secondary"):
            with st.spinner("Loading results..."):
                try:
                    fit_data_base_dir = st.session_state.get(
                        "fit_data_base_dir", "fit_data_base"
                    )
                    (
                        st.session_state["reader"],
                        st.session_state["model_config"],
                        st.session_state["model_config_save"],
                    ) = read_results(
                        st.session_state["test_id"],
                        fit_data_base_dir,
                    )
                    st.success("✅ Results loaded successfully!")

                except Exception as e:
                    st.error(f"❌ Error loading results: {e!s}")

    with col2:
        st.subheader("📈 Fitting Status")

        # Display fitting progress/status
        if "reader" in st.session_state:
            reader = st.session_state["reader"]

            # Display basic statistics
            with st.container():
                col_a, col_b, col_c = st.columns(3)
                with col_a:
                    st.metric("Samples", reader.get_chain().shape[0])
                with col_b:
                    st.metric("Chains", reader.get_chain().shape[1])
                with col_c:
                    st.metric("Parameters", reader.get_chain().shape[2])

            st.success("🎉 Fitting results are available for analysis!")
        else:
            st.info("⏳ No fitting results available yet")


def main():
    st.set_page_config(
        page_title="PL Temp Fit Workflow",
        page_icon="🔬",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    # App header
    st.title("🔬 PL Temperature Fitting Workflow")
    st.markdown(
        "*Comprehensive analysis tool for photoluminescence temperature-dependent measurements*"
    )

    # Sidebar configuration
    with st.sidebar:
        st.header("📁 Directory Configuration")

        figures_dir = st.text_input(
            "Figures Directory",
            value="figures",
            help="Directory to save generated plots",
        )
        fit_data_base_dir = st.text_input(
            "Fit Database Directory",
            value="fit_data_base",
            help="Directory for fit configurations and results",
        )
        fit_data_dir = st.text_input(
            "Fit Data Directory",
            value="fit_data",
            help="Directory for processed data files",
        )

        # Store in session state
        st.session_state["figures_dir"] = figures_dir
        st.session_state["fit_data_base_dir"] = fit_data_base_dir
        st.session_state["fit_data_dir"] = fit_data_dir

        # Ensure directories exist
        ensure_directories(figures_dir, fit_data_base_dir, fit_data_dir)
        st.success("✅ Directories configured")

        # Display workflow status
        display_workflow_status()

    # Main content with tabs
    tab1, tab2, tab3, tab4 = st.tabs(
        ["📂 Data Management", "⚙️ Model Config", "🔄 Fitting", "📊 Analysis"]
    )

    with tab1:
        data_management_tab()

    with tab2:
        model_configuration_tab()

    with tab3:
        fitting_tab()

    with tab4:
        st.header("📊 Results Analysis")
        if "reader" not in st.session_state:
            st.warning("⚠️ Please complete fitting and load results first")
        else:
            st.success(
                "✅ Results loaded - Use the interactive plotting interface below"
            )
            st.info(
                "🎨 **Interactive Plots**: All analysis plots are now interactive! You can zoom, pan, hover for details, and download plots."
            )
            plot_selection()


if __name__ == "__main__":
    main()
