# Generated by Copilot
from pathlib import Path

from pl_temp_fit import config_utils


def generate_and_save_model_config(
    params,
    csv_name,
    temperature_list,
    hws,
    temperature_lifetimes_exp,
    max_abs_pos_exp,
    fit_data_base_dir,
    fit_data_dir,
    test_id="",
):
    """Generate and save the model configuration using the provided parameters."""
    fixed_parameters_dict = params["fixed_parameters"]
    params_to_fit_init = params["params_to_fit_init"]
    min_bounds = params["min_bounds"]
    max_bounds = params["max_bounds"]
    uncertainty = params["uncertainty"]
    optimization = params["optimization"]

    model_config, test_id = config_utils.save_model_config(
        csv_name_pl=Path(csv_name),
        Temp_std_err=uncertainty["temp_std_err"],
        hws_std_err=uncertainty["hws_std_err"],
        relative_intensity_std_error_pl=uncertainty[
            "relative_intensity_std_error_pl"
        ],
        temperature_list_pl=temperature_list,
        hws_pl=hws,
        noise_sigma=uncertainty["noise_sigma"],
        fixed_parameters_dict=fixed_parameters_dict,
        params_to_fit_init=params_to_fit_init,
        min_bounds=min_bounds,
        max_bounds=max_bounds,
        num_iteration_max_likelihood=optimization[
            "num_iteration_max_likelihood"
        ],
        coeff_spread=optimization["coeff_spread"],
        nsteps=optimization["nsteps"],
        num_coords=optimization["num_coords"],
        database_folder=str(Path(fit_data_base_dir) / ""),
        data_folder=str(Path(fit_data_dir) / ""),
        temperature_lifetimes_exp=temperature_lifetimes_exp,
        max_abs_pos_exp=max_abs_pos_exp,
        test_id=test_id,
    )
    return model_config, test_id
