# Generated by Copilot
import pandas as pd


def read_lifetime_data(lifetime_csv):
    """Read and parse the lifetime data CSV."""
    df_lifetime = pd.read_csv(lifetime_csv)
    temperature_lifetimes_exp = {
        f"{row['Temperature (K)']}": row["Lifetime (s)"]
        for _, row in df_lifetime.iterrows()
    }
    max_abs_pos_exp = df_lifetime["Max Abs Pos Exp"].max()
    return temperature_lifetimes_exp, max_abs_pos_exp
