# Generated by Copilot
"""Utility functions for handling model parameters in Streamlit applications.

This module provides functions to create and manage parameter input forms
for photoluminescence fitting models, including exciton parameters with
bounds and fixed/variable toggles.
"""

from __future__ import annotations

import streamlit as st


def _create_exciton_parameter_row(
    label: str,
    initial_value: float,
    min_value: float,
    max_value: float,
    key_prefix: str,
) -> tuple[bool, float, float, float]:
    """Create a row of inputs for an exciton parameter with fixed checkbox, initial value, and bounds.

    Parameters
    ----------
    label : str
        Label for the parameter
    initial_value : float
        Default initial value
    min_value : float
        Default minimum bound
    max_value : float
        Default maximum bound
    key_prefix : str
        Unique key prefix for Streamlit widgets

    Returns
    -------
    Tuple[bool, float, float, float]
        Tuple of (fixed_checkbox_value, parameter_value, min_bound, max_bound)

    """
    # Generated by Copilot
    col1, col2, col3, col4 = st.columns([1, 2, 2, 2])
    with col1:
        fixed = st.checkbox("Fixed", key=f"{key_prefix}_fixed", value=False)
    with col2:
        value = st.number_input(
            label, value=initial_value, key=f"{key_prefix}_value"
        )
    with col3:
        min_val = st.number_input(
            "Min", value=min_value, key=f"{key_prefix}_min"
        )
    with col4:
        max_val = st.number_input(
            "Max", value=max_value, key=f"{key_prefix}_max"
        )

    return fixed, value, min_val, max_val


def get_D_parameters() -> dict[str, dict]:
    """Get the default parameters for the D (DataParams)."""
    return [
        {"name": "log_kEXCT", "value": 11, "min": 8, "max": 14, "fixed": True},
        {
            "name": "RCTE",
            "value": 1e20,
            "min": 1e18,
            "max": 1e22,
            "fixed": True,
        },
        {"name": "nie", "value": 1.5, "min": 1, "max": 2, "fixed": True},
    ]


def get_LightParameters() -> dict[str, dict]:
    return [
        {
            "name": "laser_hw",
            "value": 1.5,
            "min": 1.0,
            "max": 2.0,
            "fixed": True,
        },
        {
            "name": "Laser_B",
            "value": 0.1,
            "min": 0.0,
            "max": 2.0,
            "fixed": True,
        },
    ]


def get_CT_parameters() -> dict[str, dict]:
    return [
        {"name": "off", "value": 1, "min": 0, "max": 1, "fixed": True},
        {
            "name": "E",
            "value": 1.4,
            "min": 1.0,
            "max": 1.5,
            "fixed": True,
        },
        {
            "name": "sigma",
            "value": 0.04,
            "min": 0.001,
            "max": 0.1,
            "fixed": True,
        },
        {
            "name": "Li",
            "value": 7.8e-2,
            "min": 0.03,
            "max": 0.2,
            "fixed": True,
        },
        {
            "name": "Lo",
            "value": 0.11,
            "min": 0.03,
            "max": 0.2,
            "fixed": True,
        },
        {
            "name": "hO",
            "value": 0.159,
            "min": 0.1,
            "max": 0.2,
            "fixed": True,
        },
        {
            "name": "vmhigh",
            "value": 2,
            "min": 1.0,
            "max": 10.0,
            "fixed": True,
        },
        {
            "name": "vmlow",
            "value": 15,
            "min": 10,
            "max": 50,
            "fixed": True,
        },
        {
            "name": "numbrstates",
            "value": 20,
            "min": 10,
            "max": 50,
            "fixed": True,
        },
        {
            "name": "disorder_ext",
            "value": 0.1,
            "min": 0.01,
            "max": 0.5,
            "fixed": True,
        },
        {
            "name": "fosc",
            "value": 5.0,
            "min": 0.0001,
            "max": 10.0,
            "fixed": True,
        },
    ]


def get_exciton_parameters() -> dict[str, dict]:
    return [
        {"name": "off", "value": 0, "min": 0, "max": 1, "fixed": True},
        {
            "name": "E",
            "value": 1.5,
            "min": 1.3,
            "max": 1.9,
            "fixed": False,
        },
        {
            "name": "sigma",
            "value": 0.04,
            "min": 0.001,
            "max": 0.1,
            "fixed": False,
        },
        {
            "name": "Li",
            "value": 7.8e-2,
            "min": 0.03,
            "max": 0.2,
            "fixed": False,
        },
        {
            "name": "Lo",
            "value": 0.11,
            "min": 0.03,
            "max": 0.2,
            "fixed": False,
        },
        {
            "name": "hO",
            "value": 0.159,
            "min": 0.1,
            "max": 0.2,
            "fixed": False,
        },
        {
            "name": "vmhigh",
            "value": 2,
            "min": 1.0,
            "max": 10.0,
            "fixed": True,
        },
        {
            "name": "vmlow",
            "value": 15,
            "min": 10,
            "max": 50,
            "fixed": True,
        },
        {
            "name": "numbrstates",
            "value": 20,
            "min": 10,
            "max": 50,
            "fixed": True,
        },
        {
            "name": "disorder_ext",
            "value": 0.1,
            "min": 0.01,
            "max": 0.5,
            "fixed": True,
        },
        {
            "name": "fosc",
            "value": 5.0,
            "min": 0.0001,
            "max": 10.0,
            "fixed": True,
        },
    ]


def model_parameters_form():
    """Display and collect model parameters from the user via Streamlit widgets."""
    with st.expander("Model Parameters"):
        with st.expander("Uncertainty Parameters"):
            temp_std_err = st.number_input("Temp Std Err", value=10.0)
            hws_std_err = st.number_input("HWS Std Err", value=0.005)
            relative_intensity_std_error_pl = st.number_input(
                "Relative Intensity Std Error PL", value=0.05
            )
            noise_sigma = st.number_input("Noise Sigma", value=0.001)
            error_in_max_abs_pos = st.number_input(
                "Error in Max Abs Pos", value=0.01
            )
            relative_error_lifetime = st.number_input(
                "Relative Error Lifetime", value=0.05
            )
        with st.expander("Optimization Parameters"):
            num_iteration_max_likelihood = st.number_input(
                "Num Iteration Max Likelihood", value=5
            )
            coeff_spread = st.number_input("Coeff Spread", value=0.5)
            nsteps = st.number_input("nsteps", value=10)
            num_coords = st.number_input("num_coords", value=32)

        # --- Flexible Exciton Parameters ---
        with st.expander("Exciton Parameters"):
            st.session_state["state_params"] = get_exciton_parameters()
            ex_params = st.session_state["state_params"]
            # Parameter descriptions for tooltips
            param_descriptions = {
                # EX and CT
                "E": "Mean energy of the state (eV)",
                "sigma": "Standard deviation of the state energy (eV)",
                "Li": "High frequency reorganization energy (eV)",
                "Lo": "Low frequency reorganization energy (eV)",
                "hO": "Vibronic mode energy (eV)",
                "off": "State is off (0=on, 1=off)",
                "vmhigh": "Number of high vibrational states to consider",
                "vmlow": "Number of low vibrational states to consider",
                "numbrstates": "Number of states to consider",
                "disorder_ext": "Extension of disorder Gaussian distribution (eV)",
                "fosc": "Oscillator strength",
                # D
                "log_kEXCT": "Log10 of Exciton to CT rate constant (unitless)",
                "RCTE": "Ratio of DOS of CT to EX (unitless)",
                "nie": "Refractive index",
                # Light
                "laser_hw": "Laser photon energy (eV)",
                "Laser_B": "Laser bandwidth (eV)",
            }

            for i, param in enumerate(ex_params):
                cols = st.columns([2, 0.3, 2, 2, 2, 1, 1])
                param_name = param["name"]
                name_input = cols[0].text_input(
                    f"Name {i}",
                    value=param_name,
                    key=f"ex_name_{i}",
                    label_visibility="hidden",
                )
                param["name"] = name_input
                info_icon = "ℹ️"
                if param_name in param_descriptions:
                    cols[1].markdown(
                        f"<span title='{param_descriptions[param_name]}'>{info_icon}</span>",
                        unsafe_allow_html=True,
                    )
                else:
                    cols[1].markdown("", unsafe_allow_html=True)
                param["value"] = cols[2].number_input(
                    "Value", value=param["value"], key=f"ex_value_{i}"
                )
                param["min"] = cols[3].number_input(
                    "Min", value=param["min"], key=f"ex_min_{i}"
                )
                param["max"] = cols[4].number_input(
                    "Max ", value=param["max"], key=f"ex_max_{i}"
                )
                param["fixed"] = cols[5].checkbox(
                    "Fixed", value=param["fixed"], key=f"ex_fixed_{i}"
                )
            fixed_ex_params = {
                p["name"]: p["value"] for p in ex_params if p["fixed"]
            }

            # Build EX dicts from flexible parameters
            ex_init = {
                p["name"]: p["value"] for p in ex_params if not p["fixed"]
            }
            ex_min = {p["name"]: p["min"] for p in ex_params if not p["fixed"]}
            ex_max = {p["name"]: p["max"] for p in ex_params if not p["fixed"]}

        # --- Flexible CT Parameters ---
        with st.expander("CT State Parameters"):
            st.session_state["ct_state_params"] = get_CT_parameters()
            ct_params = st.session_state["ct_state_params"]
            for i, param in enumerate(ct_params):
                cols = st.columns([2, 0.3, 2, 2, 2, 1, 1])
                param_name = param["name"]
                name_input = cols[0].text_input(
                    f"CT Name {i}",
                    value=param_name,
                    key=f"ct_name_{i}",
                    label_visibility="hidden",
                )
                param["name"] = name_input
                info_icon = "ℹ️"
                if param_name in param_descriptions:
                    cols[1].markdown(
                        f"<span title='{param_descriptions[param_name]}'>{info_icon}</span>",
                        unsafe_allow_html=True,
                    )
                else:
                    cols[1].markdown("", unsafe_allow_html=True)
                param["value"] = cols[2].number_input(
                    "Value", value=param["value"], key=f"ct_value_{i}"
                )
                param["min"] = cols[3].number_input(
                    "Min", value=param["min"], key=f"ct_min_{i}"
                )
                param["max"] = cols[4].number_input(
                    "Max ", value=param["max"], key=f"ct_max_{i}"
                )
                param["fixed"] = cols[5].checkbox(
                    "Fixed", value=param["fixed"], key=f"ct_fixed_{i}"
                )
            fixed_ct_params = {
                p["name"]: p["value"] for p in ct_params if p["fixed"]
            }
            ct_init = {
                p["name"]: p["value"] for p in ct_params if not p["fixed"]
            }
            ct_min = {p["name"]: p["min"] for p in ct_params if not p["fixed"]}
            ct_max = {p["name"]: p["max"] for p in ct_params if not p["fixed"]}
        # --- D Parameters ---
        with st.expander("D Parameters"):
            d_params = get_D_parameters()
            for i, param in enumerate(d_params):
                cols = st.columns([2, 0.3, 2, 2, 2, 1, 1])
                param_name = param["name"]
                name_input = cols[0].text_input(
                    f"D Name {i}",
                    value=param_name,
                    key=f"d_name_{i}",
                    label_visibility="hidden",
                )
                param["name"] = name_input
                info_icon = "ℹ️"
                if param_name in param_descriptions:
                    cols[1].markdown(
                        f"<span title='{param_descriptions[param_name]}'>{info_icon}</span>",
                        unsafe_allow_html=True,
                    )
                else:
                    cols[1].markdown("", unsafe_allow_html=True)
                param["value"] = cols[2].number_input(
                    "Value", value=param["value"], key=f"d_value_{i}"
                )
                param["min"] = cols[3].number_input(
                    "Min", value=param["min"], key=f"d_min_{i}"
                )
                param["max"] = cols[4].number_input(
                    "Max ", value=param["max"], key=f"d_max_{i}"
                )
                param["fixed"] = cols[5].checkbox(
                    "Fixed", value=param["fixed"], key=f"d_fixed_{i}"
                )
            fixed_d_params = {
                p["name"]: p["value"] for p in d_params if p["fixed"]
            }
            d_init = {
                p["name"]: p["value"] for p in d_params if not p["fixed"]
            }
            d_min = {p["name"]: p["min"] for p in d_params if not p["fixed"]}
            d_max = {p["name"]: p["max"] for p in d_params if not p["fixed"]}
        # --- Light Parameters ---
        with st.expander("Light Parameters"):
            I0_params = get_LightParameters()
            for i, param in enumerate(I0_params):
                cols = st.columns([2, 0.3, 2, 2, 2, 1, 1])
                param_name = param["name"]
                name_input = cols[0].text_input(
                    f"Light Name {i}",
                    value=param_name,
                    key=f"light_name_{i}",
                    label_visibility="hidden",
                )
                param["name"] = name_input
                info_icon = "ℹ️"
                if param_name in param_descriptions:
                    cols[1].markdown(
                        f"<span title='{param_descriptions[param_name]}'>{info_icon}</span>",
                        unsafe_allow_html=True,
                    )
                else:
                    cols[1].markdown("", unsafe_allow_html=True)
                param["value"] = cols[2].number_input(
                    "Value", value=param["value"], key=f"light_value_{i}"
                )
                param["min"] = cols[3].number_input(
                    "Min", value=param["min"], key=f"light_min_{i}"
                )
                param["max"] = cols[4].number_input(
                    "Max ", value=param["max"], key=f"light_max_{i}"
                )
                param["fixed"] = cols[5].checkbox(
                    "Fixed", value=param["fixed"], key=f"light_fixed_{i}"
                )
            fixed_light_params = {
                p["name"]: p["value"] for p in I0_params if p["fixed"]
            }
            I0_init = {
                p["name"]: p["value"] for p in I0_params if not p["fixed"]
            }
            I0_min = {p["name"]: p["min"] for p in I0_params if not p["fixed"]}
            I0_max = {p["name"]: p["max"] for p in I0_params if not p["fixed"]}

    return {
        "uncertainty": {
            "temp_std_err": temp_std_err,
            "hws_std_err": hws_std_err,
            "relative_intensity_std_error_pl": relative_intensity_std_error_pl,
            "noise_sigma": noise_sigma,
            "error_in_max_abs_pos": error_in_max_abs_pos,
            "relative_error_lifetime": relative_error_lifetime,
        },
        "fixed_parameters": {
            "EX": fixed_ex_params,
            "CT": fixed_ct_params,
            "D": fixed_d_params,
            "I0": fixed_light_params,
        },
        "params_to_fit_init": {
            "EX": ex_init,
            "CT": ct_init,
            "D": d_init,
            "I0": I0_init,
        },
        "min_bounds": {
            "EX": ex_min,
            "CT": ct_min,
            "D": d_min,
            "I0": I0_min,
        },
        "max_bounds": {
            "EX": ex_max,
            "CT": ct_max,
            "D": d_max,
            "I0": I0_max,
        },
        "optimization": {
            "num_iteration_max_likelihood": num_iteration_max_likelihood,
            "coeff_spread": coeff_spread,
            "nsteps": nsteps,
            "num_coords": num_coords,
        },
    }
