# Generated by Copilot
from pathlib import Path
from pl_temp_fit import Exp_data_utils

def ensure_directories(figures_dir, fit_data_base_dir, fit_data_dir):
    Path(figures_dir).mkdir(parents=True, exist_ok=True)
    Path(fit_data_base_dir).mkdir(parents=True, exist_ok=True)
    Path(fit_data_dir).mkdir(parents=True, exist_ok=True)

def load_and_plot_data(csv_name, figures_dir):
    exp_data, temperature_list, hws = Exp_data_utils.read_data(csv_name)
    fig, ax = Exp_data_utils.plot_pl_data(
        exp_data, temperature_list, hws, title="Experimental Data"
    )
    fig_path = Path(figures_dir) / "example_PL_data_Y6.png"
    fig.savefig(fig_path)
    return exp_data, temperature_list, hws, fig, str(fig_path)

def modify_and_plot_data(csv_name, hws_limits, step, temperature_list, figures_dir):
    csv_name = Exp_data_utils.change_wavelength_range(
        Path(csv_name),
        hws_limits=list(hws_limits),
        step=step,
        temperature_list=temperature_list,
    )
    if csv_name:
        csv_name = Path(csv_name)
        exp_data, temperature_list, hws = Exp_data_utils.read_data(csv_name)
        fig, ax = Exp_data_utils.plot_pl_data(
            exp_data, temperature_list, hws, title=csv_name.name.split("/")[-1]
        )
        fig_path = Path(figures_dir) / csv_name.name.split("/")[-1].replace('.csv', '.png')
        fig.savefig(fig_path)
        return exp_data, temperature_list, hws, fig, str(fig_path), csv_name
    return None, None, None, None, None, None
